
development:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_dev
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5


production:
  <% if ENV['DATABASE_URL'] %>
    url: <%= ENV['DATABASE_URL'] %>
  <% else %>
    adapter: postgresql
    encoding: unicode
    database: <%= ENV['DATABASE_NAME'] || 'sharedesk_prod' %>
    username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
    password: <%= ENV['DATABASE_PASSWORD'] %>
    host: <%= ENV['DATABASE_HOST'] %>
    port: <%= ENV['DATABASE_PORT'] || 5432 %>
  <% end %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
 