
development:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_dev
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5


test:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_test
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5


production:
  adapter: postgresql
  encoding: unicode
  database: sharedesk_prod
  username: postgres
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: localhost
  port: 5432
  pool: 5
 